// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type IncrementItem struct {
	ID       string `json:"_id"`
	Quantity int    `json:"quantity"`
}

type Item struct {
	ID       string `json:"_id"`
	Name     string `json:"name"`
	Quantity int    `json:"quantity"`
}
